# Generated by Django 4.1.2 on 2022-10-22 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Nume Client")),
                ("adresa", models.CharField(blank=True, max_length=300)),
                (
                    "zip_code",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Cod Postal"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=25, verbose_name="Telefon contact"
                    ),
                ),
                (
                    "email_address",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email "
                    ),
                ),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=15, verbose_name="Persoana de contact"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CrmUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254, verbose_name="User Email")),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cod_produs",
                    models.CharField(max_length=120, verbose_name="Cod Produs"),
                ),
                (
                    "nume_produs",
                    models.CharField(max_length=120, verbose_name="Nume Produs"),
                ),
                (
                    "brand_produs",
                    models.CharField(max_length=120, verbose_name="Brand"),
                ),
                ("data_ticket", models.DateTimeField(verbose_name="Data ticket")),
                ("descriere", models.TextField(blank=True)),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Aprobat"),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="database.client",
                    ),
                ),
                (
                    "tehnician",
                    models.ManyToManyField(blank=True, to="database.crmuser"),
                ),
            ],
        ),
    ]
